package Launcher.ChatFrm;

import Launcher.ChatUI.GestorImagenes;
import Launcher.ChatUI.PerfilManager;
import Launcher.ChatUI.SalaManager;

/**
 *
 * @author yakor
 */
public class FrmLobby extends javax.swing.JFrame {
    
    private PerfilManager perfil;
    private SalaManager salasManager;
    private javax.swing.DefaultListModel<String> modeloLista;
    private java.util.Map<String, javax.swing.JFrame> chatsAbiertos = new java.util.HashMap<>();
    private int indiceHover = -1;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmLobby.class.getName());

    /**
     * Creates new form FrmLobby
     */
    public FrmLobby() {
        initComponents();
        
        perfil = new PerfilManager();
        salasManager = new SalaManager();
        
        lblNombreUsuario.setText(perfil.getUsername());
        
        String base64 = perfil.getAvatarBase64();
        if (base64 != null && !base64.isEmpty()) {
            javax.swing.ImageIcon icono = GestorImagenes.decodificarBase64AImagen(base64);
            
            lblAvatar.setIcon(GestorImagenes.redimensionarIcono(icono, 100, 100)); 
        }
        
        cargarListaSalas();
    }
    
    // Método para refrescar la lista
    private void cargarListaSalas() {
        javax.swing.DefaultListModel<InfoSala> modeloLista = new javax.swing.DefaultListModel<>();
        java.util.Map<String, String> misSalas = salasManager.obtenerSalas();
        
        for (String nombreSala : misSalas.keySet()) {
            String ipYPuerto = misSalas.get(nombreSala);
            String[] partes = ipYPuerto.split(":");
            
            String ip = partes[0];
            // Si tiene 3 partes (IP:TCP:PUERTO), agarramos el protocolo. Si es viejo (IP:PUERTO), asumimos TCP.
            String protocolo = partes.length == 3 ? partes[1] : "TCP"; 
            int puerto = Integer.parseInt(partes[partes.length - 1]);
            
            InfoSala info = new InfoSala(nombreSala, ip, puerto, protocolo);
            checarEstadoPing(info); 
            
            modeloLista.addElement(info);
        }
        
        listaSalas.setModel(modeloLista); 
        listaSalas.setCellRenderer(new RenderizadorSala());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAvatar = new javax.swing.JLabel();
        btnCambiarFoto = new javax.swing.JButton();
        lblNombreUsuario = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaSalas = new javax.swing.JList<>();
        btnAgregarSala = new javax.swing.JButton();
        btnConectar = new javax.swing.JButton();
        btnRecargar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat List");
        setMaximumSize(new java.awt.Dimension(400, 800));
        setMinimumSize(new java.awt.Dimension(400, 800));
        setResizable(false);

        lblAvatar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAvatar.setMaximumSize(new java.awt.Dimension(100, 100));
        lblAvatar.setMinimumSize(new java.awt.Dimension(100, 100));
        lblAvatar.setPreferredSize(new java.awt.Dimension(100, 100));

        btnCambiarFoto.setBackground(new java.awt.Color(247, 246, 246));
        btnCambiarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Launcher.Assets/pencil-16.png"))); // NOI18N
        btnCambiarFoto.setToolTipText("Cambiar foto de perfil...");
        btnCambiarFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCambiarFoto.addActionListener(this::btnCambiarFotoActionPerformed);

        lblNombreUsuario.setFont(new java.awt.Font("Sans Serif Collection", 1, 20)); // NOI18N
        lblNombreUsuario.setText("jLabel2");
        lblNombreUsuario.setAlignmentY(0.0F);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Chats", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        listaSalas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                listaSalasMouseMoved(evt);
            }
        });
        listaSalas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaSalasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                listaSalasMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(listaSalas);

        btnAgregarSala.setText("Añadir Servidor");
        btnAgregarSala.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarSala.addActionListener(this::btnAgregarSalaActionPerformed);

        btnConectar.setText("Conectar");
        btnConectar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConectar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnConectar.addActionListener(this::btnConectarActionPerformed);

        btnRecargar.setText("Recargar");
        btnRecargar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecargar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnRecargar.addActionListener(this::btnRecargarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnAgregarSala)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConectar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(btnRecargar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarSala, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConectar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRecargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(34, 215, 28));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Launcher.Assets/large_green_circle8.png"))); // NOI18N
        jLabel1.setText("CONECTADO");

        jButton1.setBackground(java.awt.SystemColor.control);
        jButton1.setFont(new java.awt.Font("sansserif", 2, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 102, 255));
        jButton1.setText("¿No eres tú?");
        jButton1.setAlignmentY(0.0F);
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.control));
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setMargin(new java.awt.Insets(2, 0, 3, 14));
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCambiarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCambiarFoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCambiarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarFotoActionPerformed
        // TODO add your handling code here:  
        java.io.File carpeta = new java.io.File("avatares");
        
        // filtro de imágenes
        java.io.File[] archivos = carpeta.listFiles((dir, name) -> 
            name.toLowerCase().endsWith(".png") || name.toLowerCase().endsWith(".jpg")
        );

        if (archivos == null || archivos.length == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "No se encontraron imágenes. Asegúrate de tener una carpeta llamada 'avatares' con imágenes en la raíz del proyecto.", 
                "Error de Avatares", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // configuracion de lista
        javax.swing.DefaultListModel<javax.swing.JLabel> modeloLista = new javax.swing.DefaultListModel<>();
        // Carga de imágenes
        for (java.io.File f : archivos) {
            javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(f.getAbsolutePath());
            javax.swing.ImageIcon iconoChico = GestorImagenes.redimensionarIcono(iconoOriginal, 40, 40);
            
            javax.swing.JLabel etiqueta = new javax.swing.JLabel("  " + f.getName().replace(".png", ""), iconoChico, javax.swing.JLabel.LEFT);
            
            etiqueta.putClientProperty("archivoRuta", f); 
            
            modeloLista.addElement(etiqueta);
        }

        javax.swing.JList<javax.swing.JLabel> listaAvatares = new javax.swing.JList<>(modeloLista);
        listaAvatares.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        
        listaAvatares.setCellRenderer(new javax.swing.ListCellRenderer<javax.swing.JLabel>() {
            public java.awt.Component getListCellRendererComponent(javax.swing.JList<? extends javax.swing.JLabel> list, javax.swing.JLabel value, int index, boolean isSelected, boolean cellHasFocus) {
                if (isSelected) {
                    value.setBackground(list.getSelectionBackground());
                    value.setForeground(list.getSelectionForeground());
                    value.setOpaque(true);
                } else {
                    value.setBackground(list.getBackground());
                    value.setForeground(list.getForeground());
                    value.setOpaque(false);
                }
                return value;
            }
        });

        // lista en un panel
        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(listaAvatares);
        scrollPane.setPreferredSize(new java.awt.Dimension(250, 300)); 

        int seleccion = javax.swing.JOptionPane.showConfirmDialog(
                this, 
                scrollPane, 
                "Elige tu Avatar",
                javax.swing.JOptionPane.OK_CANCEL_OPTION, 
                javax.swing.JOptionPane.PLAIN_MESSAGE
        );

        // carga de iamgen
        if (seleccion == javax.swing.JOptionPane.OK_OPTION && listaAvatares.getSelectedValue() != null) {
            javax.swing.JLabel seleccionado = listaAvatares.getSelectedValue();
            
            java.io.File archivoAvatar = (java.io.File) seleccionado.getClientProperty("archivoRuta");
            
            // Convertimos a Base64 y guardamos
            String nuevoBase64 = GestorImagenes.codificarImagenABase64(archivoAvatar);
            perfil.guardarAvatar(nuevoBase64);
            
            javax.swing.ImageIcon iconoFinal = GestorImagenes.decodificarBase64AImagen(nuevoBase64);
            lblAvatar.setIcon(GestorImagenes.redimensionarIcono(iconoFinal, 100, 100));
        }
    }//GEN-LAST:event_btnCambiarFotoActionPerformed

    private void btnAgregarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSalaActionPerformed
        // TODO add your handling code here:
        String nombre = javax.swing.JOptionPane.showInputDialog(this, "Nombre de la sala (Máx 20 caracteres):");
        if (nombre == null || nombre.trim().isEmpty()) return;
        
        // --- VALIDACIÓN ---
        if (nombre.length() > 20) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "El nombre es demasiado largo. Usa 20 caracteres máximo.", 
                "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String ip = javax.swing.JOptionPane.showInputDialog(this, "IP del Servidor:");
        if (ip == null || ip.trim().isEmpty()) return;
        
        String[] opciones = {"TCP", "UDP"};
        String protocoloElegido = (String) javax.swing.JOptionPane.showInputDialog(
                this, "Selecciona el Protocolo:", "Tipo de Red", 
                javax.swing.JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);
                
        if (protocoloElegido == null) return; // Si cancela
        
        // Guardamos la IP y el protocolo
        salasManager.agregarSala(nombre, ip + ":" + protocoloElegido, 7777);
        cargarListaSalas();
    }//GEN-LAST:event_btnAgregarSalaActionPerformed

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        // TODO add your handling code here:
        InfoSala salaSeleccionada = listaSalas.getSelectedValue();
        
        if (salaSeleccionada != null) {
            // Extraemos los datos 
            String ipServidor = salaSeleccionada.ip;
            int puertoServidor = salaSeleccionada.puerto;
            String protocolo = salaSeleccionada.protocolo;
            
            // Verificamos si la sala contestó
            if (!salaSeleccionada.online) {
                int respuesta = javax.swing.JOptionPane.showConfirmDialog(this, 
                    "El servidor parece estar apagado. ¿Quieres intentar conectarte de todos modos?", 
                    "Servidor Offline", 
                    javax.swing.JOptionPane.YES_NO_OPTION, 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                    
                if (respuesta != javax.swing.JOptionPane.YES_OPTION) {
                    return; // Si dice que no, cancelamos la conexión
                }
            }
            
            System.out.println("Conectando a IP: " + ipServidor + ":" + puertoServidor + " por " + protocolo + " con usuario: " + perfil.getUsername());
            
            String claveSala = ipServidor + ":" + puertoServidor;

            if (chatsAbiertos.containsKey(claveSala)) {
                javax.swing.JFrame chatGuardado = chatsAbiertos.get(claveSala);
                
                if (chatGuardado.isDisplayable()) {
                    chatGuardado.setVisible(true);
                } else {
                    FrmChat chat = new FrmChat(salaSeleccionada, perfil);
                    chatsAbiertos.put(claveSala, chat);
                    chat.setVisible(true);
                }
            } else {
                FrmChat chat = new FrmChat(salaSeleccionada, perfil);
                chatsAbiertos.put(claveSala, chat);
                chat.setVisible(true);
            }
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecciona una sala de la lista.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnConectarActionPerformed

    private void listaSalasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaSalasMouseClicked
        // TODO add your handling code here:
      
        // Si es click derecho mostrar opciones
        if (javax.swing.SwingUtilities.isRightMouseButton(evt)) {
            
            int row = listaSalas.locationToIndex(evt.getPoint());
            listaSalas.setSelectedIndex(row); 
            
            InfoSala salaSeleccionada = listaSalas.getSelectedValue();
            if (salaSeleccionada == null) return;

            javax.swing.JPopupMenu menu = new javax.swing.JPopupMenu();
            javax.swing.JMenuItem itemEliminar = new javax.swing.JMenuItem("🗑️ Eliminar '" + salaSeleccionada.nombre + "'");
            
            itemEliminar.addActionListener(e -> {
                int confirmar = javax.swing.JOptionPane.showConfirmDialog(this, 
                    "¿Estás seguro de eliminar esta sala?", "Eliminar", 
                    javax.swing.JOptionPane.YES_NO_OPTION);
                if (confirmar == javax.swing.JOptionPane.YES_OPTION) {
                    salasManager.eliminarSala(salaSeleccionada.nombre); 
                    cargarListaSalas(); 
                }
            });
            
            menu.add(itemEliminar);
            
            menu.show(listaSalas, evt.getX(), evt.getY());
            return;
        }

        // Conectar al doble click
        if (evt.getClickCount() == 2 && javax.swing.SwingUtilities.isLeftMouseButton(evt)) {
            btnConectarActionPerformed(null); 
        }
    }//GEN-LAST:event_listaSalasMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        // desconexión de chats abiertos
        for (javax.swing.JFrame chatVentana : chatsAbiertos.values()) {
            
            if (chatVentana instanceof FrmChat) {
                ((FrmChat) chatVentana).desconectarChat();
            } else {
                chatVentana.dispose();
            }
        }
        chatsAbiertos.clear();
        
        new FrmLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void listaSalasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaSalasMouseMoved
        // TODO add your handling code here:
        int index = listaSalas.locationToIndex(evt.getPoint());
        if (index != indiceHover) {
            indiceHover = index;
            listaSalas.repaint();
        }
    }//GEN-LAST:event_listaSalasMouseMoved

    private void listaSalasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaSalasMouseExited
        // TODO add your handling code here:
        indiceHover = -1; 
        listaSalas.repaint();
    }//GEN-LAST:event_listaSalasMouseExited

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        // TODO add your handling code here:
        cargarListaSalas();
        System.out.println("Lista de salas actualizada.");
    }//GEN-LAST:event_btnRecargarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmLobby().setVisible(true));
    }

    private void checarEstadoPing(InfoSala sala) {
        try (java.net.Socket socket = new java.net.Socket()) {
            socket.connect(new java.net.InetSocketAddress(sala.ip, sala.puerto), 500);
            
            java.io.PrintWriter out = new java.io.PrintWriter(new java.io.OutputStreamWriter(socket.getOutputStream(), java.nio.charset.StandardCharsets.UTF_8), true);
            java.io.BufferedReader in = new java.io.BufferedReader(new java.io.InputStreamReader(socket.getInputStream(), java.nio.charset.StandardCharsets.UTF_8));
            
            // Mandamos el comando opara revisar el estado del servidor
            out.println("STATUS_CHECK");
            String respuesta = in.readLine();
            
            if (respuesta != null && respuesta.startsWith("STATUS:")) {
                String[] partes = respuesta.split(":");
                sala.usuarios = Integer.parseInt(partes[1]);
                sala.max = Integer.parseInt(partes[2]);
                sala.online = true;
            }
        } catch (Exception e) {
            sala.online = false; // Si hay error o no contesta a tiempo, está offline
        }
    }
    
    public class InfoSala {
        String nombre;
        String ip;
        int puerto;
        String protocolo; // NUEVO
        boolean online = false;
        int usuarios = 0;
        int max = 5;

        public InfoSala(String nombre, String ip, int puerto, String protocolo) {
            this.nombre = nombre;
            this.ip = ip;
            this.puerto = puerto;
            this.protocolo = protocolo;
        }
    }
    
    class RenderizadorSala extends javax.swing.JPanel implements javax.swing.ListCellRenderer<InfoSala> {
        private javax.swing.JLabel lblIzquierda = new javax.swing.JLabel();
        private javax.swing.JLabel lblDerecha = new javax.swing.JLabel();

        public RenderizadorSala() {
            setLayout(new java.awt.BorderLayout(10, 0)); 
            setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8)); 
            
            add(lblIzquierda, java.awt.BorderLayout.WEST);
            add(lblDerecha, java.awt.BorderLayout.EAST);
        }

        @Override
        public java.awt.Component getListCellRendererComponent(javax.swing.JList<? extends InfoSala> list, InfoSala sala, int index, boolean isSelected, boolean cellHasFocus) {
            
            // configuracion lado izq
            String estadoStr = sala.online ? "● " : "○ "; 
            lblIzquierda.setText(" " + estadoStr + " " + sala.nombre);
            lblIzquierda.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
            
            // configuracion lado der
            String redStr = (sala.ip.contains("127.0.0.1") || sala.ip.contains("localhost")) ? "Local" : "Remoto";
            
            if (sala.online) {
                lblDerecha.setText(sala.usuarios + "/" + sala.max + " | " + sala.protocolo + " | " + redStr + " ");
                lblDerecha.setForeground(new java.awt.Color(0, 150, 0));
                lblIzquierda.setForeground(java.awt.Color.BLACK);
            } else {
                lblDerecha.setText("Offline | " + sala.protocolo + " | " + redStr + " ");
                lblDerecha.setForeground(java.awt.Color.GRAY);
                lblIzquierda.setForeground(java.awt.Color.GRAY);
            }

            if (isSelected) {
                setBackground(new java.awt.Color(200, 230, 255));
                setOpaque(true);
            } else if (index == indiceHover) {
                setBackground(new java.awt.Color(235, 235, 235)); 
                setOpaque(true);
            } else {
                setBackground(list.getBackground());
                setOpaque(false);
            }

            return this;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarSala;
    private javax.swing.JButton btnCambiarFoto;
    private javax.swing.JButton btnConectar;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JList<InfoSala> listaSalas;
    // End of variables declaration//GEN-END:variables
}
